### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by zruu** [gcushen/mezzanine-api#1]
> Currently, the API is readonly with the exception of the categories resource. Categories may be created or updated over the API by a superuser. The rest of the API will also gradually be opened up for write access over forthcoming releases.

When will you ship out a new release with the improvements? I really like your API, works awesome!

**Comment by gcushen** [comment]
Thanks for your feedback! I was hoping to hear some more use cases to prioritize the features that users want most. However, it's hard to monitor the few API related posts in the Mezzanine forum, so perhaps I will start a new place specifically for API discussion. The next version is nearing completion, expect it within the next few weeks.

**Comment by sonus21** [comment]
@gcushen Any updates on next release with mezzanine 4.10 ?

**Comment by gcushen** [comment]
**Version 0.4.0 (f95a23b) is now available.** To check out the release notes and to upgrade: http://gcushen.github.io/mezzanine-api/release-notes/ . 

If installing/upgrading with Mezzanine 4.1.0 and above, the Mezzanine API url declaration requires changing as per Step 4 at http://gcushen.github.io/mezzanine-api/#installation .
