### ISSUE TITLE
Published blog posts queryset is not updating

### ISSUE THREAD

**Issue by AndreiHondrari** [gcushen/mezzanine-api#11]
I have been facing an issue regarding the `/api/posts` endpoint (at least), and it's the fact that saving a Blog Post in the Mezzanine administration page with no time specified will result in saving the article with the current UTC time. At this moment in time I would expect that `/api/posts` would return my newly published and created blog post, though it is missing. I have managed to work around this issue by providing an override to the `get_queryset` method in `mezzanine_api.views.PostViewSet`:

> def get_queryset(self):
>    return Post.objects.published()

I have been debugging this issue and I've identified that rest framework, by default, does a `queryset.all()` to refresh the published posts set, though that `.all()` literally does not refresh anything and only `Posts.objects.published()` does the trick.

**Comment by gcushen** [comment]
@AndreiHondrari thanks for all the details - I'll try to look into this and release an update if necessary.

**Comment by xobb1t** [comment]
It because queryset is set as class attribute. ```published()``` calculates datetime, and, when you set it as attr, it calculates just once on first call.
Just implement get_queryset() method instead.
