### ISSUE TITLE
Documentation needs inclusion/update about managing endpoints

### ISSUE THREAD

**Issue by silpol** [gcushen/mezzanine-api#21]
When installed, mezzanin_api exposes set of various fields/endpoints in single DB. It is unclear from documentation, how one can add/remove items in this set. [Permissions](http://gcushen.github.io/mezzanine-api/#permissions) sections says about how to control access to them, but not how to administrate availability of those endpoints. Also custom architectures covered next to none. It would be great to update documentation about it.

**Comment by gcushen** [comment]
The API includes a number of popular endpoints that users have requested and is not designed to enable administration of endpoints.

For customization, refer to the third party documentation for the underlying API framework - linked from http://gcushen.github.io/mezzanine-api/#customizing
