### ISSUE TITLE
KeyError with vanilla install?

### ISSUE THREAD

**Issue by avery-laird** [gcushen/mezzanine-api#3]
I recently upgraded my mezzanine-api version to the latest, but got the following error: 

    request = kwargs['context']['request']
    KeyError: 'context'

I originally thought it must be something with my setup, which is large and involves many customizations, so I created a new virtual environment, reinstalled all requirements, started with a fresh database, and this was the first error I got when accessing the root url localhost:8000/api/docs/. I don't know nearly enough about the inner workings of this app to begin troubleshooting, but could someone perhaps set me on the right track?

**Comment by gcushen** [comment]
@avery-laird thanks for reporting this! 

It is fixed in version 0.4.2 (f6cefc0). You can upgrade using:

    pip install -U mezzanine-api

Feel free to submit any further issues you may find or add feature requests :)

**Comment by avery-laird** [comment]
Thanks, worked like a charm! Greatly enjoying the app so far.
